baseURL = "https://rsvzuiun.github.io/"
title = "rsvzuiun"
theme = "PaperMod"
languageCode = "ja-jp"
defaultcontentlanguage = "ja"
enableEmoji = true
hasCJKLanguage = true

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[params]
DateFormat = "2006-01-02"
ShowCodeCopyButtons = true
disableSpecial1stPost = true
# hideSummary = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
mainSections = ["posts", "calc"]

[[params.socialIcons]]
name = "x"
url = "https://x.com/rsvzui/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/rsvzuiun/"

[params.editPost]
URL = "https://github.com/rsvzuiun/rsvzuiun.github.io/tree/main/content"
appendFilePath = true

[[menu.main]]
name = "記事"
pageRef = "/posts"
weight = 10
[[menu.main]]
name = "計算機"
pageRef = "/calc"
weight = 20
[[menu.main]]
name = "タグ"
pageRef = "/tags"
weight = 30
[[menu.main]]
name = "例のビューア"
url = "https://rsvzuiun.github.io/rs-item-viewer/"
weight = 40

[[module.mounts]]
source = "content"
target = "content"
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "data"
target = "data"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "i18n"
target = "i18n"
[[module.mounts]]
source = "archetypes"
target = "archetypes"
[[module.mounts]]
source = "node_modules/form-storage/dist"
target = "static/js/form-storage"
includeFiles = [
  "index.umd.js",
]
[[module.mounts]]
source = "node_modules/sortable-tablesort"
target = "static/js/sortable-tablesort"
includeFiles = [
  "sortable.min.js",
  "sortable-base.min.css",
]
[[module.mounts]]
source = "node_modules/katex/dist"
target = "static/js/katex"
includeFiles = [
  "katex.min.js",
  "katex.min.css",
  "fonts/*",
  "contrib/auto-render.min.js"
]
[[module.mounts]]
source = "external/stdlib/math-base-special-betaincinv"
target = "static/js/stdlib/math-base-special-betaincinv"
includeFiles = [
  "browser.js",
]
